"""init projects and jobs

Revision ID: 0001
Revises: 
Create Date: 2026-04-21 11:47:16.618607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('project_id', sa.CHAR(length=26), nullable=True),
    sa.Column('kind', sa.Enum('parse_novel', 'gen_storyboard', 'gen_character_asset', 'gen_scene_asset', 'render_shot', 'render_batch', 'export_video', name='job_kind'), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.CHAR(length=26), nullable=True),
    sa.Column('celery_task_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'canceled', name='job_status'), nullable=False),
    sa.Column('progress', sa.SmallInteger(), nullable=False),
    sa.Column('total', sa.SmallInteger(), nullable=True),
    sa.Column('done', sa.SmallInteger(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_project_id', 'jobs', ['project_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('stage', sa.Enum('draft', 'storyboard_ready', 'characters_locked', 'scenes_locked', 'rendering', 'ready_for_export', 'exported', name='project_stage'), nullable=False),
    sa.Column('genre', sa.String(length=64), nullable=True),
    sa.Column('ratio', sa.String(length=16), nullable=False),
    sa.Column('story', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('parsed_stats', sa.JSON(), nullable=True),
    sa.Column('setup_params', sa.JSON(), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('suggested_shots', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    op.drop_index('ix_jobs_project_id', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
