"""business tables and jobs fk cascade

Revision ID: 0002
Revises: 0001
Create Date: 2026-04-21 15:07:44.112285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('project_id', sa.CHAR(length=26), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('role_type', sa.Enum('protagonist', 'supporting', 'atmosphere', name='character_role_type'), nullable=False),
    sa.Column('is_protagonist', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('reference_image_url', sa.String(length=512), nullable=True),
    sa.Column('video_style_ref', sa.JSON(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_characters_project_id', 'characters', ['project_id'], unique=False)
    op.create_table('export_tasks',
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('project_id', sa.CHAR(length=26), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', name='export_task_status'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('video_url', sa.String(length=512), nullable=True),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('duration_sec', sa.DECIMAL(precision=6, scale=1), nullable=True),
    sa.Column('progress', sa.SmallInteger(), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_export_tasks_project_id', 'export_tasks', ['project_id'], unique=False)
    op.create_table('scenes',
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('project_id', sa.CHAR(length=26), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('theme', sa.String(length=32), nullable=True),
    sa.Column('summary', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('reference_image_url', sa.String(length=512), nullable=True),
    sa.Column('video_style_ref', sa.JSON(), nullable=True),
    sa.Column('template_id', sa.String(length=64), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scenes_project_id', 'scenes', ['project_id'], unique=False)
    op.create_table('storyboards',
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('project_id', sa.CHAR(length=26), nullable=False),
    sa.Column('idx', sa.SmallInteger(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('duration_sec', sa.DECIMAL(precision=4, scale=1), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'generating', 'succeeded', 'failed', 'locked', name='storyboard_status'), nullable=False),
    sa.Column('current_render_id', sa.CHAR(length=26), nullable=True),
    sa.Column('scene_id', sa.CHAR(length=26), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'idx', name='uq_storyboards_project_idx')
    )
    op.create_index('ix_storyboards_project_id', 'storyboards', ['project_id'], unique=False)
    op.create_index('ix_storyboards_scene_id', 'storyboards', ['scene_id'], unique=False)
    op.create_table('shot_character_refs',
    sa.Column('shot_id', sa.CHAR(length=26), nullable=False),
    sa.Column('character_id', sa.CHAR(length=26), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shot_id'], ['storyboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('shot_id', 'character_id')
    )
    op.create_table('shot_renders',
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('shot_id', sa.CHAR(length=26), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', name='shot_render_status'), nullable=False),
    sa.Column('prompt_snapshot', sa.JSON(), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('provider_task_id', sa.String(length=128), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shot_id'], ['storyboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shot_id', 'version_no', name='uq_shot_renders_shot_version')
    )
    op.create_index('ix_shot_renders_shot_id', 'shot_renders', ['shot_id'], unique=False)
    op.create_table('export_shot_snapshots',
    sa.Column('export_task_id', sa.CHAR(length=26), nullable=False),
    sa.Column('shot_id', sa.CHAR(length=26), nullable=False),
    sa.Column('render_id', sa.CHAR(length=26), nullable=False),
    sa.Column('order_idx', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['export_task_id'], ['export_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['render_id'], ['shot_renders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shot_id'], ['storyboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('export_task_id', 'shot_id')
    )
    op.create_foreign_key('fk_jobs_project_id', 'jobs', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_jobs_project_id', 'jobs', type_='foreignkey')
    op.drop_table('export_shot_snapshots')
    op.drop_index('ix_shot_renders_shot_id', table_name='shot_renders')
    op.drop_table('shot_renders')
    op.drop_table('shot_character_refs')
    op.drop_index('ix_storyboards_scene_id', table_name='storyboards')
    op.drop_index('ix_storyboards_project_id', table_name='storyboards')
    op.drop_table('storyboards')
    op.drop_index('ix_scenes_project_id', table_name='scenes')
    op.drop_table('scenes')
    op.drop_index('ix_export_tasks_project_id', table_name='export_tasks')
    op.drop_table('export_tasks')
    op.drop_index('ix_characters_project_id', table_name='characters')
    op.drop_table('characters')
    # ### end Alembic commands ###
