"""add lock_scene_asset job kind

Revision ID: 125f8a6404de
Revises: e3d40b72d466
Create Date: 2026-04-22 15:39:06.896139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '125f8a6404de'
down_revision: Union[str, None] = 'e3d40b72d466'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE jobs MODIFY COLUMN kind ENUM(
            'parse_novel', 'gen_storyboard', 'gen_character_asset', 'gen_character_asset_single', 
            'gen_scene_asset', 'gen_scene_asset_single', 'register_character_asset', 
            'lock_scene_asset', 'render_shot', 'render_batch', 'export_video'
        ) NOT NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE jobs MODIFY COLUMN kind ENUM(
            'parse_novel', 'gen_storyboard', 'gen_character_asset', 'gen_character_asset_single', 
            'gen_scene_asset', 'gen_scene_asset_single', 'register_character_asset', 
            'render_shot', 'render_batch', 'export_video'
        ) NOT NULL
    """)
    # ### end Alembic commands ###
