"""add parent_id and new job kinds

Revision ID: 9127e4141b71
Revises: 0003
Create Date: 2026-04-22 11:46:29.944405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9127e4141b71'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_characters_project_locked', table_name='characters')
    op.drop_index('ix_characters_project_protagonist_locked', table_name='characters')
    op.add_column('jobs', sa.Column('parent_id', sa.CHAR(length=26), nullable=True))
    op.create_foreign_key(None, 'jobs', 'jobs', ['parent_id'], ['id'], ondelete='CASCADE')
    op.execute("ALTER TABLE jobs MODIFY COLUMN kind ENUM('parse_novel', 'gen_storyboard', 'gen_character_asset', 'gen_character_asset_single', 'gen_scene_asset', 'gen_scene_asset_single', 'render_shot', 'render_batch', 'export_video') NOT NULL")
    op.drop_index('ix_scenes_project_locked', table_name='scenes')
    op.drop_index('ix_storyboards_project_scene', table_name='storyboards')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_storyboards_project_scene', 'storyboards', ['project_id', 'scene_id'], unique=False)
    op.create_index('ix_scenes_project_locked', 'scenes', ['project_id', 'locked'], unique=False)
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'parent_id')
    op.create_index('ix_characters_project_protagonist_locked', 'characters', ['project_id', 'is_protagonist', 'locked'], unique=False)
    op.create_index('ix_characters_project_locked', 'characters', ['project_id', 'locked'], unique=False)
    # ### end Alembic commands ###
